### ISSUE TITLE
Issues with integrant init using duct.module.datomic with datomic-starter database on local system

### ISSUE THREAD

**Issue by wilsonalmeida** [hden/duct.module.datomic#11]
Shouldn't the ```(into  [] (datomic/list-databases client {}))``` be ```(into #{} (datomic/list-database client {}))``` as
otherwise ```(contains? (into #{} (datomic/list-databases client {})) db-name)``` returns ```nil```.  The return value of ```(into [] (datomic/list-databases client {}))``` in my case is ```["musicdb"]``` and ```(contains? ["musicdb"] "musicdb")``` returns ```false```.  I'm using a ```datomic-starter``` on a local dev machine.  Since the expression is evaluated as ```false```, it tries to create the database again, even though it exists.  I changed it to ```#{}``` in my local copy and that works.

Here's the relevant code from ```src/duct/database/datomic.clj```
```(defn- connect-ensure-database
  "Ensure that a database named db-name exists. Returns a connection."
  [client db-name]
  {:pre [(and (satisfies? client-protocols/Client client)
              (string? db-name))]}
  (when-not (contains? (into #{} (datomic/list-databases client {}))
                       db-name)
    (datomic/create-database client {:db-name db-name}))
  (datomic/connect client {:db-name db-name}))
```

**Comment by hden** [comment]
Thanks! 🙏 

It's now published as `0.1.0-SNAPSHOT`
